apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-be.fullname" . }}
  labels:
    {{- include "nodejs-be.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nodejs-be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nodejs-be.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
            {{if .value}}
              value: {{ .value | quote }}
            {{else if .valueFrom}}
              valueFrom:
                fieldRef:
                  fieldPath: {{.valueFrom.fieldRef.fieldPath}}
            {{end}}
          {{- end }}
          {{- $secretsFile := printf "%s-%s" (include "nodejs-be.fullname" .) "secrets" -}}
          {{- range .Values.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretsFile }}
                  key: {{ .name }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP